name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Select the service to deploy'
        required: true
        default: 'auth'
        type: choice
        options:
          - auth
          - product
          - transaction

jobs:
  build-docker-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          echo cd services/${{ github.event.inputs.service }}
          echo install, ${{ github.event.inputs.service }}

      - name: Run tests
        run: |
          echo cd services/${{ github.event.inputs.service }}
          echo test, ${{ github.event.inputs.service }}

  deploy-docker-dev:
    runs-on: ubuntu-latest
    needs: build-docker-dev

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Deploy
        run: |
          echo deploy/${{ github.event.inputs.service }}
