name: Manual Deploy Development

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Select the service to deploy'
        required: true
        type: choice
        options:
          - auth
          - product
          - transaction

jobs:
  build-docker-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo cd services/${{ github.event.inputs.service }}
          echo install, ${{ github.event.inputs.service }}

      - name: Run tests
        run: |
          echo cd services/${{ github.event.inputs.service }}
          echo test, ${{ github.event.inputs.service }}

  deploy-docker-dev:
    runs-on: ubuntu-latest
    needs: build-docker-dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Deploy
        run: |
          echo deploy/${{ github.event.inputs.service }}
